import { Link } from 'react-router-dom'
import { ArtifactTypeBadge, Button, DetailDrawer, MonospaceValue, ProvenanceChain, StructuredDataViewer, TimestampValue } from '..'
import type { TimelineEventRecord } from '../../types'
import { TimelineEventTypeBadge } from './TimelineEventTypeBadge'

export function TimelineEventDrawer({ event, caseId, open, onOpenChange }: { event: TimelineEventRecord | null; caseId: string; open: boolean; onOpenChange: (open: boolean) => void }) { return <DetailDrawer open={open} onOpenChange={onOpenChange} title="Timeline event" description="Persisted normalized observation with source timestamp semantics.">{event && <div className="space-y-5"><div className="flex flex-wrap gap-2"><TimelineEventTypeBadge type={event.event_type} /><ArtifactTypeBadge type={event.artifact_type} /></div><dl className="divide-y divide-border-subtle rounded-md border border-border-subtle bg-surface-inset"><Field label="Event ID"><MonospaceValue>{event.id}</MonospaceValue></Field><Field label="Event time"><TimestampValue value={event.event_time} semantics={event.time_semantics} /></Field><Field label="Raw time">{event.raw_time ? <MonospaceValue>{event.raw_time}</MonospaceValue> : <span className="text-text-muted">Not provided</span>}</Field><Field label="Time source"><MonospaceValue>{event.time_source}</MonospaceValue></Field><Field label="Time semantics">{event.time_semantics}</Field><Field label="Timestamp precision"><MonospaceValue>{event.timestamp_precision}</MonospaceValue></Field><Field label="Source identifier">{event.source_identifier ? <MonospaceValue>{event.source_identifier}</MonospaceValue> : <span className="text-text-muted">Not provided</span>}</Field><Field label="Parser">{event.parser_name} <MonospaceValue className="text-xs">v{event.parser_version}</MonospaceValue></Field></dl><ProcessIdentity metadata={event.metadata} /><Section title="Event metadata"><StructuredDataViewer value={event.metadata} label="Timeline event metadata" /></Section><section><h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-text-muted">Provenance</h3><ProvenanceChain nodes={[{ label: 'Evidence', id: event.evidence_id, to: `/cases/${caseId}/evidence/${event.evidence_id}` }, { label: 'Artifact', id: event.artifact_id, to: `/cases/${caseId}/artifacts/${event.artifact_id}` }, { label: 'Artifact record', id: event.artifact_record_id }, { label: 'Timeline event', id: event.id }]} /><div className="mt-3"><Link to={`/cases/${caseId}/artifacts/${event.artifact_id}`}><Button variant="secondary">Open source artifact</Button></Link></div></section><Section title="Stored provenance metadata"><StructuredDataViewer value={event.provenance} label="Timeline provenance metadata" /></Section></div>}</DetailDrawer> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid min-w-0 gap-1 px-3 py-2.5 sm:grid-cols-[9rem_minmax(0,1fr)]"><dt className="text-xs font-semibold uppercase tracking-wide text-text-muted">{label}</dt><dd className="min-w-0 break-words text-sm text-text-secondary">{children}</dd></div> }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-text-muted">{title}</h3>{children}</section> }
function ProcessIdentity({ metadata }: { metadata: Record<string, unknown> }) { const name = typeof metadata.process_name === 'string' ? metadata.process_name : null; const path = typeof metadata.process_path === 'string' ? metadata.process_path : null; const source = metadata.process_identity_source; if (!name && !path && !source) return null; return <section className="rounded-md border border-border-subtle bg-surface-inset p-3"><h3 className="text-xs font-semibold uppercase tracking-wide text-text-muted">Observed process identity</h3>{name && <p className="mt-2 text-sm text-text-secondary">Process <MonospaceValue>{name}</MonospaceValue></p>}{path && <p className="mt-2 text-sm text-text-secondary">Path <MonospaceValue>{path}</MonospaceValue></p>}{source !== undefined && <div className="mt-3"><StructuredDataViewer value={source} label="Process identity source" /></div>}<p className="mt-2 text-xs text-text-muted">Displayed from normalized source event data; no intent, attribution, or maliciousness is inferred.</p></section> }
