import { Link } from 'react-router-dom'
import { ArtifactTypeBadge, Button, MonospaceValue, ProvenanceChain, StructuredDataViewer, TimestampValue } from '..'
import type { CorrelationSupportingEvent, FindingRecord } from '../../types'
import { TimelineEventTypeBadge } from '../timeline/TimelineEventTypeBadge'

export function FindingProvenance({ finding }: { finding: FindingRecord }) { return <div className="space-y-5"><section><h2 className="text-sm font-semibold text-text-primary">Correlation Basis</h2><dl className="mt-3 divide-y divide-border-subtle rounded-md border border-border-subtle bg-surface-inset"><Field label="Correlation match"><MonospaceValue>{finding.correlation_match_id}</MonospaceValue></Field><Field label="Correlation run"><MonospaceValue>{finding.correlation_run_id}</MonospaceValue></Field><Field label="Rule"><MonospaceValue>{finding.rule_id}</MonospaceValue> <span className="text-text-muted">v{finding.rule_version}</span></Field><Field label="Match basis">{typeof finding.metadata.match_basis === 'string' ? <MonospaceValue>{finding.metadata.match_basis}</MonospaceValue> : <span className="text-text-muted">Not exposed</span>}</Field></dl><Link className="mt-3 inline-block" to={`/cases/${finding.case_id}/correlations`}><Button variant="secondary">Open correlation workspace</Button></Link></section><section><h2 className="text-sm font-semibold text-text-primary">Supporting Events</h2><div className="mt-3 space-y-3" role="list" aria-label="Finding supporting timeline events">{finding.supporting_events.map((event) => <SupportingEvent key={event.id} event={event} finding={finding} />)}</div><p className="mt-3 text-xs text-text-muted">The finding response does not include full raw timestamp semantics. Use the persisted Timeline workspace for those authoritative fields.</p><Link className="mt-3 inline-block" to={`/cases/${finding.case_id}/timeline`}><Button variant="secondary">Open Timeline workspace</Button></Link></section><section><h2 className="mb-2 text-sm font-semibold text-text-primary">Finding Metadata</h2><StructuredDataViewer value={finding.metadata} label="Finding metadata" /></section></div> }

function SupportingEvent({ event, finding }: { event: CorrelationSupportingEvent; finding: FindingRecord }) { return <article role="listitem" className="min-w-0 rounded-md border border-border-subtle bg-surface-base p-3"><div className="flex flex-wrap gap-2"><TimelineEventTypeBadge type={event.event_type} /><ArtifactTypeBadge type={event.artifact_type} /></div><dl className="mt-3 divide-y divide-border-subtle"><Field label="Timeline event"><MonospaceValue>{event.id}</MonospaceValue></Field><Field label="Event time"><TimestampValue value={event.event_time} /></Field><Field label="Source identifier">{event.source_identifier ? <MonospaceValue>{event.source_identifier}</MonospaceValue> : <span className="text-text-muted">Not provided</span>}</Field></dl><div className="mt-3"><StructuredDataViewer value={event.metadata} label={`Metadata for supporting event ${event.id}`} /></div><div className="mt-4"><ProvenanceChain nodes={[{ label: 'Finding', id: finding.id }, { label: 'Correlation match', id: finding.correlation_match_id }, { label: 'Timeline event', id: event.id }, { label: 'Artifact record', id: event.artifact_record_id }, { label: 'Artifact', id: event.artifact_id, to: `/cases/${finding.case_id}/artifacts/${event.artifact_id}` }, { label: 'Evidence', id: event.evidence_id, to: `/cases/${finding.case_id}/evidence/${event.evidence_id}` }]} /></div><p className="mt-3 text-xs text-text-muted">Evidence hash records are available from the linked evidence detail; they are not duplicated in this finding response.</p></article> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid min-w-0 gap-1 px-3 py-2.5 sm:grid-cols-[9rem_minmax(0,1fr)]"><dt className="text-xs font-semibold uppercase tracking-wide text-text-muted">{label}</dt><dd className="min-w-0 break-words text-sm text-text-secondary">{children}</dd></div> }
