import { useEffect, useState } from 'react'
import { Save } from 'lucide-react'
import { Button, ErrorState, SuccessNotice } from '..'
import type { FindingConfidence, FindingRecord, FindingSeverity, FindingStatus, FindingUpdateRequest } from '../../types'
import { getErrorMessage } from '../../utils'

const control = 'mt-1 h-9 w-full rounded-md border border-border-subtle bg-surface-inset px-3 text-sm text-text-primary hover:border-border-strong focus:border-accent'

export function FindingReviewForm({ finding, pending, error, onSave }: { finding: FindingRecord; pending: boolean; error: unknown; onSave: (payload: FindingUpdateRequest, onSuccess: () => void) => void }) {
  const [status, setStatus] = useState<FindingStatus>(finding.status)
  const [severity, setSeverity] = useState<FindingSeverity>(finding.severity)
  const [confidence, setConfidence] = useState<FindingConfidence>(finding.confidence)
  const [notes, setNotes] = useState(finding.analyst_notes ?? '')
  const [saved, setSaved] = useState(false)
  useEffect(() => { setStatus(finding.status); setSeverity(finding.severity); setConfidence(finding.confidence); setNotes(finding.analyst_notes ?? '') }, [finding])
  const changed = status !== finding.status || severity !== finding.severity || confidence !== finding.confidence || notes !== (finding.analyst_notes ?? '')
  function reset() { setStatus(finding.status); setSeverity(finding.severity); setConfidence(finding.confidence); setNotes(finding.analyst_notes ?? ''); setSaved(false) }
  function submit(event: React.FormEvent) { event.preventDefault(); const payload: FindingUpdateRequest = {}; if (status !== finding.status) payload.status = status; if (severity !== finding.severity) payload.severity = severity; if (confidence !== finding.confidence) payload.confidence = confidence; if (notes !== (finding.analyst_notes ?? '')) payload.analyst_notes = notes || null; if (!Object.keys(payload).length) return; setSaved(false); onSave(payload, () => setSaved(true)) }
  return <form onSubmit={submit} className="space-y-4" aria-labelledby="analyst-review"><div><h2 id="analyst-review" className="text-sm font-semibold text-text-primary">Analyst Review</h2><p className="mt-1 text-xs text-text-muted">These fields are analyst-review metadata. They do not modify the backend-generated finding description or provenance.</p></div>{saved && <SuccessNotice message="Finding review saved from the authoritative backend response." />}{Boolean(error) && <ErrorState title="Finding update failed" description={getErrorMessage(error)} />}<div className="grid gap-3 sm:grid-cols-3"><ReviewSelect label="Status" value={status} values={['OPEN', 'REVIEWED', 'RESOLVED', 'DISMISSED']} onChange={(value) => setStatus(value as FindingStatus)} /><ReviewSelect label="Severity" value={severity} values={['INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL']} onChange={(value) => setSeverity(value as FindingSeverity)} /><ReviewSelect label="Confidence" value={confidence} values={['LOW', 'MEDIUM', 'HIGH']} onChange={(value) => setConfidence(value as FindingConfidence)} /></div><label className="block text-xs font-semibold uppercase tracking-wide text-text-muted">Analyst notes<textarea className="mt-2 min-h-36 w-full resize-y rounded-md border border-border-subtle bg-surface-inset p-3 text-sm leading-6 text-text-primary placeholder:text-text-muted hover:border-border-strong focus:border-accent" maxLength={20000} value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Add examiner review context without changing the finding description." /><span className="mt-1 block text-right font-mono text-[11px] font-normal normal-case text-text-muted">{notes.length} / 20,000</span></label><div className="flex flex-wrap justify-end gap-2"><Button type="button" variant="ghost" disabled={!changed || pending} onClick={reset}>Cancel changes</Button><Button type="submit" loading={pending} disabled={!changed} leadingIcon={<Save aria-hidden="true" className="size-4" />}>Save review</Button></div></form>
}
function ReviewSelect({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <label className="text-xs font-semibold uppercase tracking-wide text-text-muted">{label}<select className={control} value={value} onChange={(event) => onChange(event.target.value)}>{values.map((item) => <option key={item} value={item}>{item}</option>)}</select></label> }
