import { Link } from 'react-router-dom'
import { ArtifactTypeBadge, Badge, Button, DetailDrawer, MonospaceValue, ProvenanceChain, StructuredDataViewer, TimestampValue } from '..'
import type { CorrelationMatchRecord, CorrelationSupportingEvent } from '../../types'
import { TimelineEventTypeBadge } from '../timeline/TimelineEventTypeBadge'

export function CorrelationMatchDrawer({ match, caseId, open, onOpenChange }: { match: CorrelationMatchRecord | null; caseId: string; open: boolean; onOpenChange: (open: boolean) => void }) {
  return <DetailDrawer open={open} onOpenChange={onOpenChange} title="Correlation match" description="Backend-produced deterministic relationship between persisted timeline observations.">{match && <div className="space-y-5"><dl className="divide-y divide-border-subtle rounded-md border border-border-subtle bg-surface-inset"><Field label="Match ID"><MonospaceValue>{match.id}</MonospaceValue></Field><Field label="Correlation run"><MonospaceValue>{match.correlation_run_id}</MonospaceValue></Field><Field label="Rule"><MonospaceValue>{match.rule_id}</MonospaceValue> <Badge>v{match.rule_version}</Badge></Field><Field label="Match basis"><MonospaceValue>{match.match_basis}</MonospaceValue></Field><Field label="Temporal delta"><MonospaceValue>{match.temporal_delta_seconds} seconds</MonospaceValue></Field><Field label="Created"><TimestampValue value={match.created_at} /></Field></dl><section className="rounded-md border border-accent/25 bg-accent/5 p-3"><h3 className="text-xs font-semibold uppercase tracking-wide text-text-muted">Backend explanation</h3><p className="mt-2 text-sm leading-6 text-text-secondary">{match.explanation}</p><p className="mt-2 text-xs text-text-muted">This match records deterministic identity and temporal consistency. It does not establish causation, intent, attribution, or maliciousness.</p></section><Section title={`Matched events (${match.supporting_events.length})`}><div className="space-y-3" role="list" aria-label="Matched timeline events">{match.supporting_events.map((event) => <SupportingEvent key={event.id} event={event} caseId={caseId} matchId={match.id} />)}</div><p className="mt-3 text-xs text-text-muted">The correlation response provides a bounded event representation. Open the Timeline workspace for complete raw time, source, semantics, and precision fields.</p><Link className="mt-3 inline-block" to={`/cases/${caseId}/timeline`}><Button variant="secondary">Open Timeline workspace</Button></Link></Section><Section title="Match metadata"><StructuredDataViewer value={match.metadata} label="Correlation match metadata" /></Section></div>}</DetailDrawer>
}

function SupportingEvent({ event, caseId, matchId }: { event: CorrelationSupportingEvent; caseId: string; matchId: string }) { return <article role="listitem" className="min-w-0 rounded-md border border-border-subtle bg-surface-base p-3"><div className="flex flex-wrap gap-2"><TimelineEventTypeBadge type={event.event_type} /><ArtifactTypeBadge type={event.artifact_type} /></div><dl className="mt-3 grid gap-2 text-sm"><Field label="Event ID"><MonospaceValue>{event.id}</MonospaceValue></Field><Field label="Event time"><TimestampValue value={event.event_time} /></Field><Field label="Source identifier">{event.source_identifier ? <MonospaceValue>{event.source_identifier}</MonospaceValue> : <span className="text-text-muted">Not provided</span>}</Field></dl><div className="mt-3"><StructuredDataViewer value={event.metadata} label={`Metadata for timeline event ${event.id}`} /></div><div className="mt-4"><ProvenanceChain nodes={[{ label: 'Evidence', id: event.evidence_id, to: `/cases/${caseId}/evidence/${event.evidence_id}` }, { label: 'Artifact', id: event.artifact_id, to: `/cases/${caseId}/artifacts/${event.artifact_id}` }, { label: 'Artifact record', id: event.artifact_record_id }, { label: 'Timeline event', id: event.id }, { label: 'Correlation match', id: matchId }]} /></div><details className="mt-3"><summary className="cursor-pointer text-xs font-semibold text-accent">Stored provenance metadata</summary><div className="mt-2"><StructuredDataViewer value={event.provenance} label={`Provenance for timeline event ${event.id}`} /></div></details></article> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid min-w-0 gap-1 px-3 py-2.5 sm:grid-cols-[9rem_minmax(0,1fr)]"><dt className="text-xs font-semibold uppercase tracking-wide text-text-muted">{label}</dt><dd className="min-w-0 break-words text-sm text-text-secondary">{children}</dd></div> }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-text-muted">{title}</h3>{children}</section> }
