import { useState } from 'react'
import { ArrowLeft, ShieldCheck } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { ApiError } from '../api'
import { Button, ErrorState, HashValue, LoadingState, MonospaceValue, NotFoundState, PageHeader, StatusBadge, SuccessNotice, TimestampValue } from '../components'
import { ReportArtifactPanel } from '../components/reports/ReportArtifactPanel'
import { useDownloadReport, useReport } from '../hooks'
import { getErrorMessage } from '../utils'

export function ReportDetailPage() {
  const { caseId, reportId = '' } = useParams()
  const reportQuery = useReport(reportId)
  const downloadMutation = useDownloadReport(reportId)
  const [downloaded, setDownloaded] = useState(false)
  if (reportQuery.isPending) return <LoadingState label="Loading report metadata" />
  if (reportQuery.error instanceof ApiError && reportQuery.error.status === 404) return <NotFoundState title="Report not found" description="The requested report does not exist or is no longer available." />
  if (reportQuery.isError || !reportQuery.data) return <ErrorState title="Unable to load report" description={getErrorMessage(reportQuery.error)} onRetry={() => void reportQuery.refetch()} />
  const report = reportQuery.data
  if (caseId && report.case_id !== caseId) return <NotFoundState title="Report not available for this case" description="The requested report does not belong to the case in this route." />
  function download() { setDownloaded(false); downloadMutation.mutate(undefined, { onSuccess: (file) => { const url = URL.createObjectURL(file.blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = file.filename ?? `report-${report.id}.${report.artifacts[0]?.format ?? 'bin'}`; anchor.hidden = true; document.body.append(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url); setDownloaded(true) } }) }
  return <div className="space-y-5"><PageHeader eyebrow="Forensic report" title="Report Inspection" description="Read-only report metadata and independently hashed rendered artifact delivery." breadcrumbs={[{ label: 'Cases', to: '/cases' }, { label: report.case_id, to: `/cases/${report.case_id}/overview` }, { label: 'Reports', to: `/cases/${report.case_id}/reports` }, { label: report.id }]} actions={<Link to={`/cases/${report.case_id}/reports`}><Button variant="ghost" leadingIcon={<ArrowLeft aria-hidden="true" className="size-4" />}>Back to reports</Button></Link>} />
    {downloaded && <SuccessNotice message="The report artifact download was prepared from the backend response." />}{downloadMutation.isError && <ErrorState title="Report download failed" description={getErrorMessage(downloadMutation.error)} />}
    <section className="rounded-md border border-border-subtle bg-surface-base p-4"><div className="flex flex-wrap items-center gap-2"><StatusBadge status={report.status} /><span className="rounded-sm border border-border-strong px-2 py-0.5 font-mono text-xs uppercase text-text-secondary">v{report.report_version}</span></div><dl className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Report ID"><MonospaceValue>{report.id}</MonospaceValue></Field><Field label="Case ID"><MonospaceValue>{report.case_id}</MonospaceValue></Field><Field label="Report type"><MonospaceValue>{report.report_type}</MonospaceValue></Field><Field label="Generated by">{report.generated_by}</Field><Field label="Generated at"><TimestampValue value={report.generated_at} /></Field><Field label="Created at"><TimestampValue value={report.created_at} /></Field></dl><div className="mt-4 border-t border-border-subtle pt-4"><HashValue label="SNAPSHOT SHA-256" value={report.content_hash} /><p className="mt-2 text-xs leading-5 text-text-muted">This is the deterministic immutable report-snapshot digest. It is not a source evidence hash and is distinct from the rendered artifact digest below.</p></div></section>
    <section className="rounded-md border border-border-subtle bg-surface-base p-4"><div className="mb-3 flex items-center gap-2"><ShieldCheck aria-hidden="true" className="size-4 text-accent" /><h2 className="text-sm font-semibold text-text-primary">Report Artifacts</h2></div>{report.artifacts.length ? <div className="space-y-3">{report.artifacts.map((artifact) => <ReportArtifactPanel key={artifact.id} artifact={artifact} pending={downloadMutation.isPending} onDownload={download} />)}</div> : <p className="text-sm text-text-muted">No rendered artifact metadata was returned by the backend.</p>}</section>
    <section className="rounded-md border border-border-subtle bg-surface-inset p-4"><h2 className="text-sm font-semibold text-text-primary">Immutable delivery record</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-text-secondary">This report cannot be edited, renamed, deleted, or overwritten through the application. Case changes require generation of a new historical report record. The API does not expose the snapshot body in report detail, so this workspace does not reconstruct or preview report sections.</p></section>
  </div>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="min-w-0"><dt className="text-xs font-semibold uppercase tracking-wide text-text-muted">{label}</dt><dd className="mt-1 min-w-0 break-words text-sm text-text-secondary">{children}</dd></div> }
