import { useEffect, useState } from 'react'
import { FilePlus2 } from 'lucide-react'
import { Button, Dialog, ErrorState } from '..'
import type { ReportCreateRequest, ReportFormat } from '../../types'
import { getErrorMessage } from '../../utils'

export function GenerateReportDialog({ open, onOpenChange, pending, error, onGenerate }: { open: boolean; onOpenChange: (open: boolean) => void; pending: boolean; error: unknown; onGenerate: (payload: ReportCreateRequest) => void }) {
  const [format, setFormat] = useState<ReportFormat>('pdf')
  useEffect(() => { if (!open) setFormat('pdf') }, [open])
  return <Dialog open={open} onOpenChange={onOpenChange} title="Generate forensic report" description="Create a new immutable backend report snapshot and one rendered report artifact."><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); onGenerate({ format, report_type: 'FORENSIC_INVESTIGATION_REPORT' }) }}><div className="rounded-md border border-border-subtle bg-surface-inset p-3"><p className="text-xs font-semibold uppercase tracking-wide text-text-muted">Report type</p><p className="mt-1 font-mono text-sm text-text-primary">FORENSIC_INVESTIGATION_REPORT</p><p className="mt-2 text-xs text-text-muted">The backend supports one versioned report type. Existing reports are never overwritten.</p></div><label className="block text-xs font-semibold uppercase tracking-wide text-text-muted">Rendered format<select className="mt-2 h-11 w-full rounded-md border border-border-subtle bg-surface-inset px-3 text-sm text-text-primary hover:border-border-strong focus:border-accent" value={format} onChange={(event) => setFormat(event.target.value as ReportFormat)}><option value="json">JSON — canonical machine-readable snapshot</option><option value="html">HTML — self-contained printable document</option><option value="pdf">PDF — portable forensic report</option></select></label>{Boolean(error) && <ErrorState title="Report generation failed" description={getErrorMessage(error)} />}<p className="text-xs leading-5 text-text-muted">Generation uses existing database observations and analysis. It does not reparse evidence or create new forensic conclusions.</p><div className="flex justify-end gap-2"><Button type="button" variant="ghost" disabled={pending} onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" loading={pending} leadingIcon={<FilePlus2 aria-hidden="true" className="size-4" />}>{pending ? 'Generating report' : 'Generate report'}</Button></div></form></Dialog>
}
